#!/bin/bash

INSTDIR=/tmp/dnspc
INSTDIR=.

#/usr/bin/env python $INSTDIR/setup.py install

WHICHINIT=$($INSTDIR/install/whichinit.sh)

if $WHICHINIT='upstart'; then
    cp $INSTDIR/install/dnspc.conf /etc/init/
elif $WHICHINIT='lsb'; then
    cp $INSTDIR/install/dnspc /etc/init.d/
fi
