#!/bin/bash

INSTDIR=/tmp/dnspc
INSTDIR=.

WHICHINIT=$($INSTDIR/install/whichinit.sh)

if $WHICHINIT='upstart'; then
    cp $INSTDIR/install/dnspc.conf /etc/init/
    service dnspc start
elif $WHICHINIT='lsb'; then
    cp $INSTDIR/install/dnspc /etc/init.d/
    /etc/init.d/dnspc start
elif $WHICHINIT='systemd'; then
    cp $INSTDIR/install/dnspc.service /usr/lib/systemd/system/
    ln -fs /usr/lib/systemd/system/dnspc.service /etc/systemd/system/multi-user.wants/
    systemctl start dnspc
fi
